spring:
  datasource:
    url: jdbc:oracle:thin:@//20.42.17.102:1521/XEPDB1
    username: poc_hab_sura
    password: Nttdata2025.
    driver-class-name: oracle.jdbc.OracleDriver

queue:
  table-name: QUEUE_STATUS
  columns-to-return:
    - ID
    - QUEUE_NAME
    - STATUS
    - APIGEE_PROXY_NAME
